import Header from "@/components/Primary/Header/Header";
import "./globals.css";
import { Poppins, Spectral } from "next/font/google";

export const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  preload: false,
});
export const spectralFont = Spectral({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  preload: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
